In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
li=[4,5,6,7,"sudh", 34.565,True]
a1=np.array(li)
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [5]:
a2=np.array([[1,2,3,],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [7]:
a1.ndim ## ndim() is used to return total n- Dimensional array. 

1

In [8]:
a2.ndim

2

In [9]:
a3.ndim

3

In [10]:
a1.size  # size() is Used to return total element value in a array

7

In [11]:
a2.size

6

In [12]:
a3.size

9

In [18]:
a1.shape  #  shape() is used to return how much row & column are their in a array (ex:- 2 row & 3 Column)

(7,)

In [19]:
a2.shape

(2, 3)

In [20]:
a3.shape #  Read loud as this :- Read this array (1,3,3)  :- 3 cross 3 & one such kind of dimension.

(1, 3, 3)

In [21]:
np.random.randint(2,50)  # random.randint() is used to generate a random integer number.

29

In [22]:
np.random.randint(2,50, (2,3,4)) # Read this array (2,3,4) :- 3 cross 4 & 2 such kind of dimension.

array([[[17, 15, 41, 49],
        [42,  4, 25, 45],
        [14, 38, 22, 34]],

       [[21, 26, 28, 36],
        [12, 42, 12, 25],
        [49, 25, 15, 45]]])

In [23]:
np.random.rand(2,3)

array([[0.45956285, 0.37022135, 0.09673817],
       [0.66114396, 0.04214962, 0.74443577]])

In [24]:
a4=np.random.randn(4,4)

In [25]:
a4

array([[-1.19505814,  0.83494501,  1.0977731 , -1.56896943],
       [ 1.87314029, -0.98547886, -0.64347918, -1.53845601],
       [-0.74663628, -1.14655084, -2.63053127, -0.0987695 ],
       [ 0.1155075 ,  1.11943472, -0.93895973, -1.29218268]])

In [27]:
a4.reshape(3,3)

ValueError: cannot reshape array of size 16 into shape (3,3)

In [26]:
a4.reshape(2,8) # reshape() is used to change the shape of previous array.

array([[-1.19505814,  0.83494501,  1.0977731 , -1.56896943,  1.87314029,
        -0.98547886, -0.64347918, -1.53845601],
       [-0.74663628, -1.14655084, -2.63053127, -0.0987695 ,  0.1155075 ,
         1.11943472, -0.93895973, -1.29218268]])

In [28]:
a4.reshape(8,2)

array([[-1.19505814,  0.83494501],
       [ 1.0977731 , -1.56896943],
       [ 1.87314029, -0.98547886],
       [-0.64347918, -1.53845601],
       [-0.74663628, -1.14655084],
       [-2.63053127, -0.0987695 ],
       [ 0.1155075 ,  1.11943472],
       [-0.93895973, -1.29218268]])

In [29]:
a4.reshape(1,16)

array([[-1.19505814,  0.83494501,  1.0977731 , -1.56896943,  1.87314029,
        -0.98547886, -0.64347918, -1.53845601, -0.74663628, -1.14655084,
        -2.63053127, -0.0987695 ,  0.1155075 ,  1.11943472, -0.93895973,
        -1.29218268]])

In [36]:
a4.reshape(2,-1)  # Any negative number will automatically shape of a Factorial number.

array([[-1.19505814,  0.83494501,  1.0977731 , -1.56896943,  1.87314029,
        -0.98547886, -0.64347918, -1.53845601],
       [-0.74663628, -1.14655084, -2.63053127, -0.0987695 ,  0.1155075 ,
         1.11943472, -0.93895973, -1.29218268]])

In [37]:
a4.reshape(2,2,4)

array([[[-1.19505814,  0.83494501,  1.0977731 , -1.56896943],
        [ 1.87314029, -0.98547886, -0.64347918, -1.53845601]],

       [[-0.74663628, -1.14655084, -2.63053127, -0.0987695 ],
        [ 0.1155075 ,  1.11943472, -0.93895973, -1.29218268]]])

In [38]:
a4.reshape(1,1,1,1,1,1,1,2,2,4)

array([[[[[[[[[[-1.19505814,  0.83494501,  1.0977731 ,
                -1.56896943],
               [ 1.87314029, -0.98547886, -0.64347918,
                -1.53845601]],

              [[-0.74663628, -1.14655084, -2.63053127,
                -0.0987695 ],
               [ 0.1155075 ,  1.11943472, -0.93895973,
                -1.29218268]]]]]]]]]])

In [39]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [40]:
a1[0]

'4'

In [41]:
a1[2:6]

array(['6', '7', 'sudh', '34.565'], dtype='<U32')

In [42]:
a1[::-1]

array(['True', '34.565', 'sudh', '7', '6', '5', '4'], dtype='<U32')

In [43]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [44]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
a2[0]

array([1, 2, 3])

In [46]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [47]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [53]:
a2[[0,1],[2,2]]

array([3, 6])

In [56]:
a5=np.random.randint(2,90,(6,5))
a5

array([[32, 25,  4, 47,  6],
       [14, 77, 47, 47, 44],
       [20, 37, 50, 29, 61],
       [33, 12, 49, 24, 73],
       [31, 81, 30, 51, 89],
       [64, 16, 63, 87, 47]])

In [57]:
a5[a5>40]

array([47, 77, 47, 47, 44, 50, 61, 49, 73, 81, 51, 89, 64, 63, 87, 47])

In [58]:
a5[0,1]=100 # replace (0,1) ordinate value of 55 to 100.

In [59]:
a5

array([[ 32, 100,   4,  47,   6],
       [ 14,  77,  47,  47,  44],
       [ 20,  37,  50,  29,  61],
       [ 33,  12,  49,  24,  73],
       [ 31,  81,  30,  51,  89],
       [ 64,  16,  63,  87,  47]])

In [60]:
a6=np.random.randint(0,3,(3,3))

In [61]:
a7=np.random.randint(0,3,(3,3))

In [62]:
a6

array([[0, 0, 0],
       [1, 0, 2],
       [2, 1, 2]])

In [63]:
a7

array([[2, 0, 0],
       [2, 0, 1],
       [1, 2, 0]])

In [64]:
a6*a7  # Symbol * is used to give element wise multiplication.

array([[0, 0, 0],
       [2, 0, 2],
       [2, 2, 0]])

In [65]:
a6@a7 # @ - symbol is used to matrix multiplication

array([[0, 0, 0],
       [4, 4, 0],
       [8, 4, 1]])

In [66]:
a6+100

array([[100, 100, 100],
       [101, 100, 102],
       [102, 101, 102]])

In [67]:
a6*2

array([[0, 0, 0],
       [2, 0, 4],
       [4, 2, 4]])

In [68]:
a6/0

C:\Users\Aman\AppData\Local\Temp\ipykernel_14532\1058679823.py:1: RuntimeWarning:

divide by zero encountered in true_divide

C:\Users\Aman\AppData\Local\Temp\ipykernel_14532\1058679823.py:1: RuntimeWarning:

invalid value encountered in true_divide



array([[nan, nan, nan],
       [inf, nan, inf],
       [inf, inf, inf]])

In [69]:
a6

array([[0, 0, 0],
       [1, 0, 2],
       [2, 1, 2]])

In [70]:
a6**3

array([[0, 0, 0],
       [1, 0, 8],
       [8, 1, 8]], dtype=int32)

In [71]:
a8=np.zeros((4,4))
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
a9=np.ones((4,4))

In [73]:
a9

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [74]:
a9+10

array([[11., 11., 11., 11.],
       [11., 11., 11., 11.],
       [11., 11., 11., 11.],
       [11., 11., 11., 11.]])

In [75]:
a9+np.array([1,2,3,4]) # this function is called Broadcasting operation. #row wise addition

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [77]:
a9

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [82]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [79]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [84]:
np.array([[1,2,3,4]]).T+a9

array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [85]:
a6

array([[0, 0, 0],
       [1, 0, 2],
       [2, 1, 2]])

In [86]:
a6.T # T is a Transpose function for transporting array froom Row to column & wis

array([[0, 1, 2],
       [0, 0, 1],
       [0, 2, 2]])

In [87]:
a5

array([[ 32, 100,   4,  47,   6],
       [ 14,  77,  47,  47,  44],
       [ 20,  37,  50,  29,  61],
       [ 33,  12,  49,  24,  73],
       [ 31,  81,  30,  51,  89],
       [ 64,  16,  63,  87,  47]])

In [88]:
np.sqrt(a5)

array([[ 5.65685425, 10.        ,  2.        ,  6.8556546 ,  2.44948974],
       [ 3.74165739,  8.77496439,  6.8556546 ,  6.8556546 ,  6.63324958],
       [ 4.47213595,  6.08276253,  7.07106781,  5.38516481,  7.81024968],
       [ 5.74456265,  3.46410162,  7.        ,  4.89897949,  8.54400375],
       [ 5.56776436,  9.        ,  5.47722558,  7.14142843,  9.43398113],
       [ 8.        ,  4.        ,  7.93725393,  9.32737905,  6.8556546 ]])

In [89]:
np.exp(a5)

array([[7.89629602e+13, 2.68811714e+43, 5.45981500e+01, 2.58131289e+20,
        4.03428793e+02],
       [1.20260428e+06, 2.75851345e+33, 2.58131289e+20, 2.58131289e+20,
        1.28516001e+19],
       [4.85165195e+08, 1.17191424e+16, 5.18470553e+21, 3.93133430e+12,
        3.10429794e+26],
       [2.14643580e+14, 1.62754791e+05, 1.90734657e+21, 2.64891221e+10,
        5.05239363e+31],
       [2.90488497e+13, 1.50609731e+35, 1.06864746e+13, 1.40934908e+22,
        4.48961282e+38],
       [6.23514908e+27, 8.88611052e+06, 2.29378316e+27, 6.07603023e+37,
        2.58131289e+20]])

In [90]:
np.log10(a5)

array([[1.50514998, 2.        , 0.60205999, 1.67209786, 0.77815125],
       [1.14612804, 1.88649073, 1.67209786, 1.67209786, 1.64345268],
       [1.30103   , 1.56820172, 1.69897   , 1.462398  , 1.78532984],
       [1.51851394, 1.07918125, 1.69019608, 1.38021124, 1.86332286],
       [1.49136169, 1.90848502, 1.47712125, 1.70757018, 1.94939001],
       [1.80617997, 1.20411998, 1.79934055, 1.93951925, 1.67209786]])

In [91]:
range(10)

range(0, 10)

In [92]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [95]:
list(range(0,10,2.5))

TypeError: 'float' object cannot be interpreted as an integer

In [100]:
np.arange(10) # arange() is same function as range work.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
np.arange(1.8,10.7,2.5)  # arange() is uses in float value also.

array([1.8, 4.3, 6.8, 9.3])

In [102]:
np.linspace(2,3,num=50,retstep=True) # retstep:- jump size

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [103]:
np.logspace(2,4, num =4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [104]:
np.eye(5) ## Eye() is use for generating identical matrix where Diagonal of matrix will be 1 and rest Element will be zero.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Data Visualization using Python

In [13]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly as pl
import cufflinks as cf

In [ ]:
!pip install cufflinks

In [105]:
cf.go_offline()

In [106]:
np.random.randn(100,3)

array([[ 0.65650993, -0.35749695,  2.21287312],
       [ 0.63066981,  1.25744446,  0.47102173],
       [ 0.75990522, -0.52950156,  0.25419921],
       [-0.48446189,  0.81730676,  0.91744132],
       [ 0.29337484, -0.24626772,  2.39514201],
       [-0.13773819,  0.54888717, -0.41793902],
       [-0.01891858,  0.70000056, -0.69306   ],
       [-1.54454674, -1.04263469, -1.30352633],
       [ 1.25311581, -0.7969627 ,  0.05007864],
       [ 0.59412699,  1.46257042, -0.60252992],
       [ 0.01078782,  0.08410365,  0.10166985],
       [ 0.33938812,  1.63880764, -0.24501046],
       [-0.16891702,  0.38798974,  1.16623088],
       [-0.55268514, -1.06636879, -0.15733522],
       [ 0.76997524, -0.98524738, -0.18746568],
       [ 0.36365219,  0.2941011 ,  0.11362425],
       [-0.49170132,  0.10838696,  0.19508225],
       [ 0.29555007,  0.49114582,  0.40529123],
       [-0.45148158, -1.12789906,  1.36955703],
       [ 1.22086596, -1.73481165,  0.76721351],
       [-0.74646902,  0.36414353, -0.549

In [109]:
df=pd.DataFrame(np.random.randn(100,3), columns=['A','B','C'])

In [112]:
df.shape

(100, 3)

In [113]:
df.iplot()

In [133]:
ddf=pd.DataFrame(np.random.randint(3,100,(100,1)))
ddf.iplot()

In [134]:
ddf

0
0   12
1   18
2   67
3   31
4   92
..  ..
95  40
96   3
97  21
98  26
99   6

[100 rows x 1 columns]

In [135]:
np.random.seed(10)
pd.DataFrame(np.random.randint(3,100,100).reshape(100,1))

0
0   12
1   18
2   67
3   31
4   92
..  ..
95  40
96   3
97  21
98  26
99   6

[100 rows x 1 columns]

In [ ]:
# df1= pd.DataFrame((np.random.randint(100,3)))

In [136]:
df1=sns.load_dataset('titanic')

In [137]:
df1.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [138]:
df1.iplot(x="age",y='fare',mode='markers')

In [139]:
df1.iplot(x="age",y='pclass',mode='markers')

In [140]:
df1.iplot(x="fare",y='pclass',mode='markers')

In [141]:
df1.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [142]:
df1.iplot(x="fare",y='pclass',kind='bar')

In [143]:
df1.iplot(x="sex",y='survived',kind='bar')