In [1]:
import numpy as np
import array

In [4]:
arr=np.array([1,2,3,4,5])
type(arr)
arr

array([1, 2, 3, 4, 5])

In [5]:
arr=np.array([1,2,3,4,5,"Aman",4+5j])
arr

array(['1', '2', '3', '4', '5', 'Aman', '(4+5j)'], dtype='<U64')

In [6]:
arr=np.array([1,2,3,4,5,6.0])
arr

array([1., 2., 3., 4., 5., 6.])

In [7]:
arr=np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [9]:
arr=np.array([[1,2],[3,4],[5,6,7]])
arr

<ipython-input-9-e6f3e5808a3c>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr=np.array([[1,2],[3,4],[5,6,7]])


array([list([1, 2]), list([3, 4]), list([5, 6, 7])], dtype=object)

In [10]:
arr=np.array([[[1,2],[3,4]],[[5,6],[6,7]]])
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [6, 7]]])

In [12]:
arr=np.array([1,2,3,4,5], ndmin=3)
arr

array([[[1, 2, 3, 4, 5]]])

In [14]:
arr=np.array([1,2,3], ndmin=30)
arr

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2, 3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [15]:
arr=np.array([1,2,3], dtype=complex)
arr

array([1.+0.j, 2.+0.j, 3.+0.j])

In [22]:
arr=np.array([(1,2),(2,3)],dtype=[("a",'<i2'), ("b",'<i8')])
arr

array([(1, 2), (2, 3)], dtype=[('a', '<i2'), ('b', '<i8')])

In [25]:
type(arr[0][0])

numpy.int16

In [24]:
type(arr[0][1])

numpy.int64

In [26]:
arr=np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [30]:
type(arr[1][1])

numpy.int32

In [37]:
mat=np.mat(arr)
np.matrix(arr)

matrix([[1, 2],
        [3, 4]])

In [32]:
type(np.mat(arr))

numpy.matrix

In [34]:
l=[1,2,3,4,5,6]
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [35]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6])

In [36]:
np.asanyarray(l)

array([1, 2, 3, 4, 5, 6])

In [38]:
np.asanyarray(mat)

matrix([[1, 2],
        [3, 4]])

In [39]:
issubclass(np.matrix, np.ndarray)

True

In [40]:
issubclass(np.ndarray,np.matrix)

False

In [41]:
arr

array([[1, 2],
       [3, 4]])

In [42]:
# Shallow copy
a=arr

In [43]:
# Deep copy
b=np.copy(arr)

In [45]:
arr[0][0]= 10

In [46]:
arr

array([[10,  2],
       [ 3,  4]])

In [47]:
a

array([[10,  2],
       [ 3,  4]])

In [49]:
b

array([[1, 2],
       [3, 4]])

In [51]:
arr[0:1]

array([[10,  2]])

In [52]:
for i in arr:
    print(i)

[10  2]
[3 4]


In [54]:
type(np.fromfunction(lambda a,b : a==b,(4,4)))

numpy.ndarray

In [55]:
np.fromfunction(lambda a,b : a==b,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [56]:
np.fromfunction(lambda a,b : a*b,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [57]:
np.fromfunction(lambda a,b : a**b,(3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [58]:
np.fromfunction(lambda a,b : a/b,(3,3))

<ipython-input-58-8132ae125f12>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda a,b : a/b,(3,3))
<ipython-input-58-8132ae125f12>:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda a,b : a/b,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [62]:
gen=(i*i for i in range(5))
gen

<generator object <genexpr> at 0x00000216CA098740>

In [60]:
def test(x):
    yield x

test(5)

<generator object test at 0x00000216CA098200>

In [65]:
np.fromiter(gen,dtype=int)

array([ 0,  1,  4,  9, 16])

In [66]:
np.fromiter(range(7),dtype=int)

array([0, 1, 2, 3, 4, 5, 6])

In [67]:
np.fromstring("1,2,3,4,5,6", sep=",", dtype=int)

array([1, 2, 3, 4, 5, 6])

In [69]:
np.fromstring("1122 3323 4244 542 4236", sep=" ", dtype=complex)

array([1122.+0.j, 3323.+0.j, 4244.+0.j,  542.+0.j, 4236.+0.j])

In [74]:
x=(i**2 for i in range(10))
np.fromiter(x, dtype=int)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [75]:
l=[3,4,5,6,7]
arr=np.array(l)

In [82]:
arr1=np.array([[1,2,3,4],[5,6,7,8],[0,1,2,3]])

In [83]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [0, 1, 2, 3]])

In [84]:
arr1.ndim

2

In [85]:
arr1.size

12

In [86]:
arr1.shape

(3, 4)

In [87]:
arr1.dtype

dtype('int32')

In [88]:
arr.size

3

In [89]:
arr.ndim

1

In [93]:
arr.dtype

dtype('O')

In [94]:
arr.shape

(3,)

In [97]:
arr2=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])

In [98]:
arr2

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [99]:
arr2.size

16

In [100]:
arr2.shape

(2, 2, 4)

In [101]:
arr2.ndim

3

In [1]:
arr4=np.array([[[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]]])

<IPython.core.display.Javascript object>

In [2]:
arr4

array([[[[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[1, 2, 3, 4],
         [5, 6, 7, 8]]]])

In [4]:
arr4.shape

(1, 4, 2, 4)

In [5]:
arr4.ndim

4

In [7]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [11]:
np.arange(5.5,8,.2)

<IPython.core.display.Javascript object>

array([5.5, 5.7, 5.9, 6.1, 6.3, 6.5, 6.7, 6.9, 7.1, 7.3, 7.5, 7.7, 7.9])

In [12]:
np.linspace(1,2,5)

<IPython.core.display.Javascript object>

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [16]:
np.zeros(5)

<IPython.core.display.Javascript object>

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((5,4))

<IPython.core.display.Javascript object>

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.zeros((2,5,4))

<IPython.core.display.Javascript object>

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [19]:
np.zeros((2,5,4,1))

<IPython.core.display.Javascript object>

array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]])

In [20]:
np.ones(4)

<IPython.core.display.Javascript object>

array([1., 1., 1., 1.])

In [22]:
np.ones((2,5,4))+5

<IPython.core.display.Javascript object>

array([[[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]],

       [[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]])

In [24]:
np.empty(5)

<IPython.core.display.Javascript object>

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304, 7.74860419e-304,
       7.74860419e-304])

In [23]:
np.empty((3,4))

<IPython.core.display.Javascript object>

array([[1.11950156e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 5.93280795e-038, 6.95657770e-042,
        1.03176206e+166],
       [4.31016816e-033, 1.47835206e+185, 2.14753996e+184,
        5.19908191e+170]])

In [27]:
np.eye(4) #identity matrix

<IPython.core.display.Javascript object>

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
np.linspace([2,4],4,endpoint=False,axis=1)

<IPython.core.display.Javascript object>

array([[2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96],
       [4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  ]])

In [36]:
np.logspace([2,3],5,axis=1)

<IPython.core.display.Javascript object>

array([[   100.        ,    115.13953993,    132.57113656,
           152.64179672,    175.75106249,    202.35896477,
           232.99518105,    268.26957953,    308.88435965,
           355.64803062,    409.49150624,    471.48663635,
           542.86754393,    625.05519253,    719.685673  ,
           828.64277285,    954.09547635,   1098.54114199,
          1264.85521686,   1456.3484775 ,   1676.83293681,
          1930.69772888,   2222.99648253,   2559.5479227 ,
          2947.05170255,   3393.2217719 ,   3906.93993705,
          4498.43266897,   5179.47467923,   5963.62331659,
          6866.48845004,   7906.04321091,   9102.98177992,
         10481.13134155,  12067.92640639,  13894.95494373,
         15998.58719606,  18420.69969327,  21209.5088792 ,
         24420.53094549,  28117.68697974,  32374.57542818,
         37275.93720315,  42919.34260129,  49417.13361324,
         56898.66029018,  65512.85568596,  75431.20063355,
         86851.13737514, 100000.        ],
       [  100

In [38]:
d=np.linspace(4,7,40)
d

<IPython.core.display.Javascript object>

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [39]:
d.ndim

1

In [40]:
d.shape

(40,)

In [42]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [45]:
d.reshape(3,2,1,20)

ValueError: cannot reshape array of size 40 into shape (3,2,1,20)

In [47]:
d.reshape(1,4,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [48]:
np.random.rand(3)

<IPython.core.display.Javascript object>

array([0.35220924, 0.71334364, 0.49094134])

In [50]:
np.random.randn(2,2,3)

<IPython.core.display.Javascript object>

array([[[ 1.13238685,  0.00863861,  0.66729634],
        [ 0.61589774, -0.10946501,  1.32862777]],

       [[ 0.19344705, -1.22989844,  0.36156401],
        [ 1.59593181,  0.72791078,  1.6194762 ]]])

In [58]:
np.random.randint(1,10,(4,4))

<IPython.core.display.Javascript object>

array([[6, 7, 6, 6],
       [7, 5, 3, 8],
       [1, 9, 4, 4],
       [5, 9, 3, 3]])

In [59]:
arr=np.random.randint(3,9,(3,3))

<IPython.core.display.Javascript object>

In [60]:
arr

array([[8, 7, 5],
       [6, 6, 5],
       [7, 4, 5]])

In [63]:
arr.reshape(9,1)

array([[8],
       [7],
       [5],
       [6],
       [6],
       [5],
       [7],
       [4],
       [5]])

In [62]:
arr.reshape(1,1,9)

array([[[8, 7, 5, 6, 6, 5, 7, 4, 5]]])

In [64]:
arr.reshape(3,3,1)

array([[[8],
        [7],
        [5]],

       [[6],
        [6],
        [5]],

       [[7],
        [4],
        [5]]])

In [69]:
arr.reshape(3,-189724398)

array([[8, 7, 5],
       [6, 6, 5],
       [7, 4, 5]])

In [67]:
arr.reshape(1,-1)

array([[8, 7, 5, 6, 6, 5, 7, 4, 5]])

In [70]:
arr.max()

8

In [71]:
arr.min()

4

In [76]:
np.random.seed(1)
arr=np.random.randint(4,100,(5,5))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [77]:
arr

array([[41, 16, 76, 13, 79],
       [ 9, 83, 68, 20,  5],
       [80, 75, 10, 29, 54],
       [24, 22, 88, 15, 32],
       [33, 18, 54, 72, 91]])

In [92]:
arr[0:,[1,3]]

array([[16, 13],
       [83, 20],
       [75, 29],
       [22, 15],
       [18, 72]])

In [94]:
arr[arr>10]

array([41, 16, 76, 13, 79, 83, 68, 20, 80, 75, 29, 54, 24, 22, 88, 15, 32,
       33, 18, 54, 72, 91])

In [95]:
arr1=np.random.randint(2,4,(3,3))

<IPython.core.display.Javascript object>

In [96]:
arr2=np.random.randint(2,4,(3,3))

<IPython.core.display.Javascript object>

In [97]:
arr1

array([[3, 3, 3],
       [3, 2, 2],
       [2, 3, 3]])

In [98]:
arr2

array([[3, 3, 3],
       [3, 2, 3],
       [3, 2, 2]])

In [99]:
arr1+arr2

array([[6, 6, 6],
       [6, 4, 5],
       [5, 5, 5]])

In [100]:
arr1*arr2

array([[9, 9, 9],
       [9, 4, 6],
       [6, 6, 6]])

In [101]:
arr1@arr2

array([[27, 21, 24],
       [21, 17, 19],
       [24, 18, 21]])

In [102]:
arr1/0

<ipython-input-102-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [103]:
arr**2

array([[1681,  256, 5776,  169, 6241],
       [  81, 6889, 4624,  400,   25],
       [6400, 5625,  100,  841, 2916],
       [ 576,  484, 7744,  225, 1024],
       [1089,  324, 2916, 5184, 8281]], dtype=int32)

In [105]:
# Broadcasting
arr=np.zeros((3,4))

<IPython.core.display.Javascript object>

In [106]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [114]:
a=np.array([1,2,3,5])

<IPython.core.display.Javascript object>

In [115]:
a

array([1, 2, 3, 5])

In [116]:
arr+a

array([[1., 2., 3., 5.],
       [1., 2., 3., 5.],
       [1., 2., 3., 5.]])

In [110]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [120]:
b=np.array([5,6,7]).reshape(3,1)

<IPython.core.display.Javascript object>

In [118]:
b.reshape(3,1)

array([[5],
       [6],
       [7]])

In [121]:
arr+b

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [124]:
b=np.array([[5,6,7]])

<IPython.core.display.Javascript object>

In [126]:
b.T+arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [130]:
arr=np.random.rand(5,4)

<IPython.core.display.Javascript object>

In [131]:
arr

array([[0.82914691, 0.82960336, 0.27304997, 0.0592432 ],
       [0.67052804, 0.59306552, 0.6716541 , 0.41178788],
       [0.1975509 , 0.28962964, 0.14212014, 0.78331447],
       [0.41253884, 0.03417131, 0.62402999, 0.66063573],
       [0.29849529, 0.44613451, 0.22212455, 0.07336417]])

In [132]:
np.sqrt(arr)

<IPython.core.display.Javascript object>

array([[0.91057504, 0.91082565, 0.52254184, 0.24339926],
       [0.81885777, 0.77010747, 0.81954506, 0.641707  ],
       [0.44446698, 0.5381725 , 0.37698824, 0.88505055],
       [0.64229187, 0.18485484, 0.78995569, 0.81279501],
       [0.54634723, 0.66793301, 0.47130091, 0.27085821]])

In [133]:
np.exp(arr)

<IPython.core.display.Javascript object>

array([[2.29136316, 2.2924093 , 1.31396591, 1.06103325],
       [1.95526951, 1.80952706, 1.95747249, 1.5095142 ],
       [1.21841508, 1.33593262, 1.15271512, 2.18871469],
       [1.51064822, 1.03476186, 1.86643461, 1.93602273],
       [1.3478292 , 1.56226159, 1.24872689, 1.07612236]])

In [134]:
np.log10(arr)

<IPython.core.display.Javascript object>

array([[-0.08136851, -0.0811295 , -0.56375786, -1.22736148],
       [-0.17358306, -0.22689733, -0.17285433, -0.38532644],
       [-0.70432099, -0.53815699, -0.84734439, -0.10606385],
       [-0.38453516, -1.46633836, -0.20479454, -0.18003794],
       [-0.52506251, -0.35053419, -0.65340344, -1.13451598]])

In [135]:
np.random.randint(2,5,(5,5))

<IPython.core.display.Javascript object>

array([[4, 3, 4, 3, 2],
       [3, 3, 4, 2, 2],
       [4, 4, 3, 2, 4],
       [4, 4, 2, 2, 3],
       [3, 3, 2, 2, 3]])

In [136]:
np.log10(arr)

<IPython.core.display.Javascript object>

array([[-0.08136851, -0.0811295 , -0.56375786, -1.22736148],
       [-0.17358306, -0.22689733, -0.17285433, -0.38532644],
       [-0.70432099, -0.53815699, -0.84734439, -0.10606385],
       [-0.38453516, -1.46633836, -0.20479454, -0.18003794],
       [-0.52506251, -0.35053419, -0.65340344, -1.13451598]])

In [137]:
np.log2(arr)

<IPython.core.display.Javascript object>

array([[-0.27030036, -0.26950636, -1.87276307, -4.07720659],
       [-0.57663043, -0.7537366 , -0.57420966, -1.28002673],
       [-2.33970369, -1.78771884, -2.81481713, -0.35233648],
       [-1.27739814, -4.87107058, -0.68031274, -0.5980731 ],
       [-1.7442199 , -1.16444936, -2.17055926, -3.76878051]])

In [139]:
np.random.seed(30)
np.random.rand(2,4)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073],
       [0.96260781, 0.34666184, 0.99175099, 0.2350579 ]])